name: Android CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: create keystore file
      run: |
        echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > ${HOME}/keystore.jks
    - name: Build
      env:
        ALIAS: ${{ secrets.ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      run: |
        KEY_STORE_FILE="${HOME}/keystore.jks"
        cd StandardControls  
        nuget restore
        cd AndroidStandardControls
        msbuild "AndroidStandardControls.csproj" "/t:SignAndroidPackage" "/p:Configuration=Release" "/p:AndroidKeyStore=true" "/p:AndroidSigningKeyAlias=${ALIAS}" "/p:AndroidSigningKeyPass=${KEY_PASSWORD}" "/p:AndroidSigningKeyStore=${KEY_STORE_FILE}" "/p:AndroidSigningStorePass=${KEY_STORE_PASSWORD}"
    - name: Test app on apptest.ai
      uses: forcemax/apptestai-test@v1
      with:
        access_key: ${{ secrets.APPTEST_AI_ACCESS_KEY }}
        project_id: 1134
        binary_path: StandardControls/AndroidStandardControls/bin/Release/com.xamarin.samples.standardcontrols-Signed.apk
