name: iOS CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: use xcode 11.3.1
      run: sudo xcode-select -switch /Applications/Xcode_11.3.1.app/Contents/Developer
    - name: check lipo
      run: |
        ls -l /Applications/Xcode_11.3.1.app/Contents/Developer/usr/bin/xcodebuild
        ls -l /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
    - name: nuget restore
      working-directory: ./StandardControls
      run: nuget restore 
    - name: Prepare build
      working-directory: ./StandardControls/iOSStandardControls
      env:
        CI: true
      run: |
        bundle update --bundler
        fastlane add_plugin souyuz 
    - name: Build development package using fastlane
      working-directory: ./StandardControls/iOSStandardControls 
      env:
        CI: true
        APPLE_ID: ${{ secrets.APPLE_ID }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_CERT_REPO: ${{ secrets.FASTLANE_CERT_REPO }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
        MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
      run: fastlane beta 
    - name: Test app on apptest.ai
      uses: forcemax/apptestai-test@v1.2
      with:
        access_key: ${{ secrets.APPTEST_AI_ACCESS_KEY }}
        project_id: 1144
        binary_path: StandardControls/iOSStandardControls/bin/iPhone/Release/iOSStandardControls.ipa
